# Generated by Django 5.1.6 on 2025-04-30 07:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=django_ckeditor_5.fields.CKEditor5Field(
                max_length=500, verbose_name="Отрывок"
            ),
        ),
    ]
