# Generated by Django 5.1.6 on 2025-04-30 07:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_content_alter_article_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=django_ckeditor_5.fields.CKEditor5Field(
                max_length=100, verbose_name="Отрывок"
            ),
        ),
    ]
