# Generated by Django 5.1.6 on 2025-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(blank=True, verbose_name="Отрывок"),
        ),
    ]
