# Generated by Django 5.1.6 on 2025-05-08 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создан",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
    ]
