# Generated by Django 5.1.6 on 2025-04-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг категории")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название тега"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг тега")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название статьи"),
                ),
                ("content", models.TextField(verbose_name="Контент")),
                ("excerpt", models.TextField(verbose_name="Отрывок")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг статьи")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="articles.tag", verbose_name="Теги"),
                ),
            ],
        ),
    ]
